[flags]
hide_avg_cpu = false
dot_marker = false
rate = "1s"
cpu_left_legend = false
current_usage = false
unnormalized_cpu = false
group_processes = false
case_sensitive = false
whole_word = false
regex = false
temperature_type = "c"
default_time_value = "60s"
time_delta = 15000
hide_time = false
default_widget_type = "proc"
default_widget_count = 1
expanded = false
basic = false
use_old_network_legend = false
hide_table_gap = true
battery = true
disable_click = true
process_memory_as_value = true
tree = false
show_table_scroll_position = true
process_command = false
network_use_binary_prefix = false
network_use_bytes = false
network_use_log = false
disable_advanced_kill = false
enable_gpu = true
enable_cache_memory = false
retention = "10m"

[processes]
columns = ["PID", "Name", "CPU%", "Mem%", "R/s", "W/s", "T.Read", "T.Write", "User", "State", "GMem%", "GPU%"]

[cpu]
 default = "average"

[disk]
[name_filter]
is_list_ignored = true
list = ["/dev/sda\\d+", "/dev/nvme0n1p2"]
regex = true
case_sensitive = false
whole_word = false

[mount_filter]
is_list_ignored = true
list = ["/mnt/.*", "/boot"]
regex = true
case_sensitive = false
whole_word = false

[temperature]
[sensor_filter]
is_list_ignored = true
list = ["cpu", "wifi"]
regex = false
case_sensitive = false
whole_word = false

[network]
[interface_filter]
is_list_ignored = true
list = ["virbr0.*"]
regex = true
case_sensitive = false
whole_word = false

[styles]
theme = "gruvbox"

[styles.cpu]
all_entry_color = "green"
avg_entry_color = "red"
cpu_core_colors = ["light magenta", "light yellow", "light cyan", "light green", "light blue", "cyan", "green", "blue"]

[styles.memory]
ram_color = "light magenta"
cache_color = "light red"
swap_color = "light yellow"
arc_color = "light cyan"
gpu_colors = ["light blue", "light red", "cyan", "green", "blue", "red"]

[styles.network]
rx_color = "light magenta"
tx_color = "light yellow"
rx_total_color = "light cyan"
tx_total_color = "light green"

[styles.battery]
high_battery_color = "green"
medium_battery_color = "yellow"
low_battery_color = "red"

[styles.tables]
headers = {color = "light blue", bold = true}

[styles.graphs]
graph_color = "gray"
legend_text = {color = "gray"}

[styles.widgets]
border_color = "gray"
selected_border_color = "light blue"
widget_title = {color = "gray"}
text = {color = "gray"}
selected_text = {color = "black", bg_color = "light blue"}
disabled_text = {color = "dark gray"}

[[row]]
  ratio=30
  [[row.child]]
  type="cpu"
[[row]]
    ratio=40
    [[row.child]]
      ratio=4
      type="mem"
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="temp"
      [[row.child.child]]
        type="disk"
[[row]]
  ratio=30
  [[row.child]]
    type="net"
  [[row.child]]
    type="proc"
    default=true
