"$schema" = 'https://starship.rs/config-schema.json'

palette = "gruvbox_dark"
add_newline = true

[character] 
success_symbol = '[>>](bold blue0)'
error_symbol   = '[>>](bold red0)'
vimcmd_symbol  = '[Nor>>](bold green0)'
vimcmd_replace_symbol = '[R>>](bold green0)'
vimcmd_replace_one_symbol = '[R1>>](bold green0)'
vimcmd_visual_symbol = '[Vis>>](bold green0)'

[directory]
style = 'bold yellow0'
read_only = 'Read Only'
read_only_style = 'red0'

[sudo]
format = '[as sudo](red0)'

[lua]
format = 'via [lua](blue0)'

[git_branch]
symbol = 'branch: '
style = 'bold blue0'

[git_status]
style = 'bold yellow0'


[palettes.gruvbox_dark]
bg0_hard   = "#1d2021"
bg0        = "#282828"
bg1        = "#32302f"
bg2        = "#3c3836"
bg3        = "#504945"
bg4	   = "#7c6f64"

gray       = "#665c54"
fg0        = "#fbf1c7"
fg1        = "#ebdbb2"
fg2        = "#d5c4a1"
fg3        = "#bdae93"
fg4        = "#a89984"

red0	   = "#fb4934"
green0     = "#b8bb26"
yellow0    = "#fabd2f"
blue0      = "#83a598"
purple0    = "#d3869b"
aqua0      = "#8ec07c"
orange0    = "#fe8019"
red1       = "#cc241d"
green1     = "#98971a"
yellow1    = "#d79921"
blue1      = "#458588"
purple1    = "#b16286"
aqua1      = "#689d6a"
orange1    = "#d65d0e"

